### ISSUE TITLE
remoteagent fail to start

### ISSUE THREAD

**Issue by nirhenn** [cea-sec/ivre#269] opened 2016-07-20 07:28 UTC
When I try to work with `runscansagentdb` I get the following error:
```
ubuntu@ivre:~$ ivre runscansagentdb --daemon
Traceback (most recent call last):
   File "/usr/local/bin/ivre", line 73, in <module>
     main()
   File "/usr/local/bin/ivre", line 51, in main
     tools.get_command(possible_commands[0])()
   File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscansagentdb.py", line 223, in main
     ivre.db.db.agent.feed_all(masterid)
   File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 966, in feed_all
     self.feed(masterid, scanid)
   File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 969, in feed
     scan = self.lock_scan(scanid)
   File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1079, in lock_scan
     scan['target'] = pickle.loads(scan['target'])
TypeError: 'NoneType' object has no attribute '__getitem__'
ubuntu@ivre:~$ ivre runscansagentdb --list-scans
scan:
   - id: 578e87ca53618d07ae1e5710
   - categories:
     - ROUTABLE
   - targets added: 60
   - results fetched: 0
   - total targets to add: 100
   - available targets: 2815732132
   - internal state: (684862215, 2475232221, 148196429, 60)
   - agents:
     - 578e872453618d079051f9ee
ubuntu@ivre:~$ sudo ivre runscansagentdb --list-agents
agent:
   - id: 578e872453618d079051f9ee
   - source name: MySource
   - remote host: 127.0.0.1
   - remote path: /agent/
   - master: 578e86ee53618d078091a7c8
   - local path: /var/lib/ivre/master/5awR01
   - rsync command: rsync
   - current scan: 578e87ca53618d07ae1e5710
   - currently synced: True
   - max waiting targets: 60
   - waiting targets: 120
   - current targets: 0
   - can receive: 0
```

**Comment by p-l-** [comment] 2016-07-20 11:55
Hi,

Can you give the comprehensive list of commands you have issued to get there? Also can you report the output of `find /var/lib/ivre`?

Thanks,

Pierre

**Comment by nirhenn** [comment] 2016-08-04 14:59
Hi,

I do not find the history log for the CLI but i followed the guide for agent doc.

as for /var/liv/ivre ..

root@ivre:~# find /var/lib/ivre
/var/lib/ivre
/var/lib/ivre/master
/var/lib/ivre/master/whoami
/var/lib/ivre/master/5awR01
/var/lib/ivre/master/5awR01/input
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-Tf5smZ
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-bSUNYa
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-Y4ux98
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-CaT292
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-qAOUmO
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-F9HrjJ
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-hvDSAQ
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-AOEugd
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-NQ8xf1
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-oBjRl7
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-633Nkb
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-qNiXJ5
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-FNESar
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-n9Ouua
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-lQFxta
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-Idl2Aq
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-CTcQMX
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-Ffr4b4
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-zdX3uq
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-mMC1wh
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-6uq5dS
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-4LUj8l
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-bmwrOE
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-lltoNK
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-aS4JoP
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-cISm_Q
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-5YcZlR
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-P6CEpB
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-IC05A4
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-6670gu
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-wF7kCh
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-N3qPzr
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-n99Tet
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-vbEO7d
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-SGTJFe
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-jDXQ2W
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-VhHgNV
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-7TnvHN
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-SldLSY
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-pvjwOw
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-SKvtat
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-zYIvJT
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-WoPbYT
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-JuYdr5
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-20khxL
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-DzmtOq
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-3LGXhb
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-Ya5DP6
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-eFr8PQ
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-RMUaDc
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-QrKqQa
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-k1rEd4
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-YbvAvn
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-IaHHts
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-5XIOaT
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-66ekUM
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-vDg79O
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-6nbyYP
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-Xd427g
/var/lib/ivre/master/5awR01/input/578e87ca53618d07ae1e5710-LYYGf3
/var/lib/ivre/master/5awR01/remote
/var/lib/ivre/master/5awR01/remote/input
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-Tf5smZ
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-bSUNYa
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-Y4ux98
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-CaT292
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-qAOUmO
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-F9HrjJ
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-hvDSAQ
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-AOEugd
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-NQ8xf1
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-oBjRl7
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-633Nkb
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-qNiXJ5
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-FNESar
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-n9Ouua
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-lQFxta
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-Idl2Aq
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-CTcQMX
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-Ffr4b4
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-zdX3uq
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-mMC1wh
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-6uq5dS
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-4LUj8l
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-bmwrOE
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-lltoNK
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-aS4JoP
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-cISm_Q
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-5YcZlR
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-P6CEpB
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-IC05A4
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-6670gu
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-wF7kCh
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-N3qPzr
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-n99Tet
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-vbEO7d
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-SGTJFe
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-jDXQ2W
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-VhHgNV
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-7TnvHN
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-SldLSY
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-pvjwOw
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-SKvtat
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-zYIvJT
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-WoPbYT
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-JuYdr5
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-20khxL
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-DzmtOq
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-3LGXhb
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-Ya5DP6
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-eFr8PQ
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-RMUaDc
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-QrKqQa
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-k1rEd4
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-YbvAvn
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-IaHHts
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-5XIOaT
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-66ekUM
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-vDg79O
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-6nbyYP
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-Xd427g
/var/lib/ivre/master/5awR01/remote/input/578e87ca53618d07ae1e5710-LYYGf3
/var/lib/ivre/master/5awR01/remote/output
/var/lib/ivre/master/5awR01/remote/cur
/var/lib/ivre/master/onhold
/var/lib/ivre/master/output

**Comment by p-l-** [comment] 2016-08-04 15:17
I'm sorry but without the comprehensive command history I have no clue to understand how you triggered this bug. Can you do that again from the beginning?

**Comment by p-l-** [comment] 2016-08-09 10:43
I'm closing this one, as I cannot reproduce it and cannot work on it without further information. Please reopen it if you encounter the problem again and have recorded all the commands you have issued.

**Closed by p-l-** 2016-08-09 10:43 UTC
