### ISSUE TITLE
Docker image ivre/base lacks configuration file

### ISSUE THREAD

**Issue by python-zzk** [cea-sec/ivre#746] opened 2019-08-09 11:09 UTC
File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/scancli.py", line 122, in main
    db.db.nmap.init()
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/mongo.py", line 3476, in init
    self.db[self.columns[self.column_scans]].drop()
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 1092, in drop
    dbo.drop_collection(self.__name, session=session)
  File "/usr/lib/python2.7/dist-packages/pymongo/database.py", line 748, in drop_collection
    with self.__client._socket_for_writes() as sock_info:
  File "/usr/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 1085, in _socket_for_writes
    server = self._get_topology().select_server(writable_server_selector)
  File "/usr/lib/python2.7/dist-packages/pymongo/topology.py", line 224, in select_server
    address))
  File "/usr/lib/python2.7/dist-packages/pymongo/topology.py", line 183, in select_servers
    selector, server_timeout, address)
  File "/usr/lib/python2.7/dist-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

**Comment by p-l-** [comment] 2019-08-09 11:26
The MongoDB server is not running.

As I have no idea how you have run the client (based on the issue title, I'd guess it was using Docker, but I don't know if you have been using Vagrant, with which command lines, etc.) I cannot help you more than that. Please provide any relevant information if you still need help.

**Comment by python-zzk** [comment] 2019-08-09 11:43
> The MongoDB server is not running.
> 
> As I have no idea how you have run the client (based on the issue title, I'd guess it was using Docker, but I don't know if you have been using Vagrant, with which command lines, etc.) I cannot help you more than that. Please provide any relevant information if you still need help.

i not why ,  i use  vagrant up --no-parallel  . docker ivre/clint  ivre/db ivre/web   is normal .but input  iivre scancli --init  is error  in ivreclient .maybe the MongoDB   old version？

**Comment by p-l-** [comment] 2019-08-09 15:19
This seems to be a regression introduced by #734.

**Comment by p-l-** [comment] 2019-08-09 15:49
Two configuration files are missing from the current docker images. Once #747 has been merged, I'll let you know when new images are ready, you will just have to `docker pull` them, run `vagrant destroy` then `vagrant up --no-parallel` again.

**Closed** 2019-08-09 20:20 UTC

**Comment by p-l-** [comment] 2019-08-09 21:11
The fixed images are ready now! You can just run:
```
vagrant destroy
for i in db client web; do docker pull ivre/$i; done
vagrant up --no-parallel
```
Please report here if it still doesn't work.
Thanks for this report, happy hacking!

**Comment by python-zzk** [comment] 2019-08-10 02:59
> The fixed images are ready now! You can just run:
> 
> ```
> vagrant destroy
> for i in db client web; do docker pull ivre/$i; done
> vagrant up --no-parallel
> ```
> 
> Please report here if it still doesn't work.
> Thanks for this report, happy hacking!

OK!  Docker‘s start mode is bridge mode， i modify it  to  host mode。problem is solved。Thank you!
