### ISSUE TITLE
error plz help

### ISSUE THREAD

**Issue by 3g0r111** [cea-sec/ivre#541] opened 2018-06-24 09:54 UTC
when i install ivre after that i initialise ivre 
 ivre scancli --init
sudo ivre ipinfo --init
sudo ivre ipdata --init
sudo ivre runscansagentdb --init

ipdata return me a error: ivre ipdata --init
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/home/egor/.local/lib/python2.7/site-packages/ivre/tools/__init__.py", line 59, in get_command
    return getattr(__import__("%s.%s" % (__name__, name)).tools, name).main
  File "/home/egor/.local/lib/python2.7/site-packages/ivre/tools/ipdata.py", line 48, in <module>
    import ivre.geoiputils
  File "/home/egor/.local/lib/python2.7/site-packages/ivre/geoiputils.py", line 263, in <module>
    os.path.join(config.GEOIP_PATH, 'GeoIPCountry.csv'),
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

### IVRE Version

IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.10

Python 2.7.15 (default, May  1 2018, 05:55:50) 
[GCC 7.3.0]

Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali1 (2018-01-08) x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.6.1
    Python module py2neo: missing
    Python module sqlalchemy: 1.1.11
    Python module psycopg2: 2.7.3 (dt dec mx pq3 ext lo64)
    Python module krbV: missing
    Python module PIL: 4.3.0
    Python module MySQLdb: 1.3.10
    Python module dbus: 1.2.4
    Python module matplotlib: 2.0.0
    Python module bottle: 0.12.13

```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.5.dev46

2.7.13 (default, Feb 11 2017, 12:22:40) 
[GCC 6.3.1 20170109]

Dependencies:
    Python module Crypto: 2.6.1
	[...]

```

### Summary

Short summary.

### Expected behavior

Describe here what you would expect, if the feature you want existed,
or if the bug you report didn't exist.

### Actual behavior

If needed, describe what actually happens. Be sure to include
comprehensive output, including obscure error messages, logs from the
Web or DB server if appropriate, etc.

### How to reproduce

If needed, include the exact commands others can try to reproduce your
issue.

### More

Please include any other information that could help us. We will be
able to help you faster if we don't have to ask questions and wait for
your answers.

**Comment by p-l-** [comment] 2018-06-24 13:07
Duplicate of #505, fixed in #507. You just need to create the directory `geoip` directory in IVRE's `share` directory. This should work:
```
mkdir `python -c 'from ivre import config; print(config.guess_prefix())'`/geoip
```

**Closed by p-l-** 2018-06-24 13:07 UTC
